"""Left SHARPA hand, 22 DoF, 5 fingers, mounted with no arm.

The REAL SHARPA, as a control for the commercial hands. Every in-hand run before this
one trained on ``sharpa_capsule.json``, whose provenance reads ``method:
sharpa_capsule`` -- SHARPA rebuilt inside the design grammar, where
``build.author_hand`` writes capsules and never opens a mesh. That is a fair control
for a generated design and it is not this hand.

Everything here is imported from the same ``robot_param_constants`` tables the
arm-mounted ``sharpa_iiwa14`` spec uses, so the two cannot drift: joint order, gains,
armature, fingertip bodies and pad offset are literally the same objects. Three things
differ, and all three follow from there being no arm:

  * ``urdf_path`` is the unified hand-only description, the arm removed and the tree
    rooted at the palm.
  * ``palm_body_name`` is ``left_hand_C_MC``, the palm itself, where the arm spec uses
    ``iiwa14_link_7`` because the palm merges into the flange under
    ``merge_fixed_joints``.
  * The palm frame is the IDENTITY, not ``flange_to_palm``. ``PALM_BOX_CENTER_M`` and
    ``PALM_EXTENTS_M`` are measured in the palm's own frame, and that frame is exactly
    our convention -- x = thickness and grasp normal, y = width, z = wrist to
    fingertip. The arm spec needs ``flange_to_palm`` only to carry those points up into
    link_7. Rooting at the palm removes the transform rather than replacing it.
    ``unify_from_vendor.py`` asserts the mount chain composes to ``flange_to_palm``
    (yaw -75 deg, z 0.095 m), which is what makes that claim checkable.
"""

from __future__ import annotations

import numpy as np

from hand_sampler.build import palm_keypoints
from hand_sampler.design_space import joint_link_boxes
from hand_sampler.robot_param_constants import (
    FINGERTIP_BODY_NAMES,
    FINGERTIP_OFFSET,
    HAND_ARMATURE,
    HAND_DAMPING,
    HAND_JOINT_NAMES,
    HAND_STIFFNESS,
    PALM_BOX_CENTER_M,
    PALM_EXTENTS_M,
    hand_only_base_pos,
    hand_only_base_rot,
)
from hand_sampler.robot_spec import RobotSpec
from isaacsimenvs.pose_reaching_6d.scene_utils.robots.adjacency.sharpa_handonly import (
    SHARPA_HANDONLY_ADJACENT_LINKS,
)

URDF = "assets/urdf/unified_commercial_hands/sharpa/sharpa.urdf"
PALM_BODY = "left_hand_C_MC"

# The palm's own frame IS our convention, so there is nothing to adapt. Contrast
# Allegro, whose palm_link is (fingers, width, normal) and needs a permutation.
PALM_FRAME = np.eye(3)

# Read once, here, rather than at every run start: the env takes its tokens from the
# spec and never learns that this hand happens to have a URDF.
_BODIES, _BOXES, _VALID, _SCALE = joint_link_boxes(URDF, HAND_JOINT_NAMES)

SHARPA_HANDONLY = RobotSpec(
    name="sharpa_handonly",
    arm_name="",
    hand_name="sharpa",
    urdf_path=URDF,
    arm_joint_names=(),
    hand_joint_names=HAND_JOINT_NAMES,
    palm_body_name=PALM_BODY,
    fingertip_body_names=FINGERTIP_BODY_NAMES,
    arm_stiffness={},
    arm_damping={},
    hand_stiffness=HAND_STIFFNESS,
    hand_damping=HAND_DAMPING,
    hand_armature=HAND_ARMATURE,
    # simtoolreal used one shared offset for all five pads; kept, as in the arm spec.
    fingertip_offsets=tuple(FINGERTIP_OFFSET for _ in FINGERTIP_BODY_NAMES),
    joint_link_bodies=tuple(_BODIES),
    joint_link_boxes=_BOXES,
    joint_geometry_valid=_VALID,
    hand_scale=float(_SCALE),
    arm_default_joint_pos={},
    # All zero: SHARPA's flexion lower limits are 0, so this is the hand wide open and
    # inside every limit -- unlike Allegro, whose thumb roll excludes zero.
    hand_default_joint_pos={n: 0.0 for n in HAND_JOINT_NAMES},
    start_arm_higher_deltas={},
    palm_center_offset=tuple(float(v) for v in PALM_BOX_CENTER_M),
    palm_keypoints=tuple(
        tuple(map(float, p)) for p in palm_keypoints(PALM_BOX_CENTER_M, PALM_EXTENTS_M,
                                                    frame=PALM_FRAME)
    ),
    adjacent_links=SHARPA_HANDONLY_ADJACENT_LINKS,
    link_prim_regexes=("/World/envs/env_.*/Robot/left_.*/visuals",),
    base_pos=hand_only_base_pos(tuple(map(tuple, PALM_FRAME)), PALM_BOX_CENTER_M),
    base_rot=hand_only_base_rot(tuple(map(tuple, PALM_FRAME))),
    notes=(
        "Left SHARPA, 22 DoF, hand-only. The measured hand, not the sharpa_capsule "
        "grammar rebuild every earlier in-hand run used. URDF generated by "
        "assets/urdf/unified_commercial_hands/sharpa/unify_from_vendor.py, which "
        "extracts the subtree at left_hand_C_MC from "
        "assets/urdf/kuka_sharpa_description and asserts the removed mount chain "
        "composes to build.flange_to_palm. Joint order, gains, armature, fingertip "
        "bodies and pad offset are the same robot_param_constants objects the "
        "arm-mounted sharpa_iiwa14 spec uses, so the two cannot drift."
    ),
)

__all__ = ["SHARPA_HANDONLY", "PALM_FRAME", "URDF"]
