"""Viewers for the IsaacLab in-hand reference: wandb-style capture, and viser.

Both draw the reference env, which is manager-based and shares none of our env's
internals -- no ``scene_record``, no ``RobotSpec``, no canonical joint permutation, no
``_keypoints_max_dist``. What it does have is enough:

  * ``scene["robot"].data.joint_names`` / ``joint_pos`` -- and those names are EXACTLY
    our unified Allegro URDF's, verified as a set equality. So the hand is drawn from
    ``assets/urdf/unified_commercial_hands/allegro/allegro.urdf`` rather than from their
    USD, which a browser cannot load. Their joint ORDER differs (all ``_joint_0``, then
    all ``_joint_1``, ...), which is why every frame carries its own name list and the
    page zips by name -- sending positions in one order and names in another is how the
    pinky once appeared frozen.
  * ``scene["object"]`` root pose, and a 0.06 m cube -- measured from the stage, not
    assumed. Note that is 60 mm against our task's 45 mm.
  * ``command_manager.get_term("object_pose")`` carries ``pos_command_w`` and
    ``quat_command_w``: the goal pose, in world.

The object is drawn as a Rubik-faced cube at their size, generated by the same
``generate_handle_urdf`` our task uses, because a plain cube's orientation is
unreadable and orientation is the entire task.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np

REPO = Path("/share/portal/kk837/gen_mechanics")
# On master, so the viewer page can fetch it. See pose_viewer.GITHUB_RAW_BASE_MAIN.
ROBOT_URDF_RELPATH = "assets/urdf/unified_commercial_hands/allegro/allegro.urdf"
# The body our URDF is rooted at. Their articulation root is allegro_mount.
PALM_BODY = "palm_link"
# Measured from the stage with a UsdGeom bbox cache, not taken from their config: the
# cfg says density 400, which against this size implies 0.086 kg, while the body
# actually reports 0.264 kg -- the USD's own mass wins. The size is what a viewer needs.
DEX_CUBE_EDGE_M = 0.06


def _host(t) -> np.ndarray:
    """A numpy copy of a torch tensor on any device, or of anything array-like.

    Everything Isaac Lab hands back lives on the GPU, and numpy refuses a CUDA tensor
    outright rather than copying it, so the conversion has to be explicit.
    """
    cpu = getattr(t, "detach", None)
    if cpu is not None:
        t = t.detach().cpu()
    return np.asarray(t, dtype=float)


def _pose(pos, quat, origin=None) -> tuple[float, ...]:
    """``(x, y, z, qx, qy, qz, qw)`` -- the page's order, env-local.

    Isaac Lab hands out wxyz; the viewer page wants xyzw. Getting this backwards leaves
    a body that rotates almost correctly, which is much harder to notice than one that
    does not move at all.
    """
    p = _host(pos)
    if origin is not None:
        p = p - _host(origin)
    w, x, y, z = (float(v) for v in _host(quat))
    return (float(p[0]), float(p[1]), float(p[2]), x, y, z, w)


def capture_frame(env, env_id: int = 0) -> dict[str, Any]:
    """One frame of the reference env, in the layout ``build_pose_viewer_html`` wants."""
    inner = env.unwrapped
    robot = inner.scene["robot"]
    obj = inner.scene["object"]
    origin = inner.scene.env_origins[env_id]
    term = inner.command_manager.get_term("object_pose")
    # THE PALM BODY, NOT THE ARTICULATION ROOT. Their root is allegro_mount and our
    # unified URDF is rooted at palm_link -- the mount link is one of the things the
    # unifier drops. Using root_pos_w/root_quat_w put the hand 83.85 mm and 98.42 deg
    # out, measured, because allegro_mount_joint carries exactly that offset.
    #
    # This is the same mistake that produced three wrong answers about the reference's
    # palm tilt: its published init_state.rot describes the MOUNT, not the palm. Read at
    # the palm body instead, its grasp normal is 5.40 deg off vertical.
    palm = robot.data.body_names.index(PALM_BODY)
    return {
        "robot_joint_names": list(robot.data.joint_names),
        "robot_joint_pos": [float(v) for v in _host(robot.data.joint_pos[env_id])],
        "robot_base_pose": _pose(robot.data.body_pos_w[env_id, palm],
                                 robot.data.body_quat_w[env_id, palm], origin),
        "object_pose": _pose(obj.data.root_pos_w[env_id],
                             obj.data.root_quat_w[env_id], origin),
        "goal_pose": _pose(term.pos_command_w[env_id], term.quat_command_w[env_id], origin),
    }


def object_urdf_text(edge_m: float = DEX_CUBE_EDGE_M) -> str:
    """A Rubik-faced cube of their size, for drawing only.

    Reuses the task's own generator so the faces, colours and inset match what the
    other viewers show, and so there is one implementation of "a cube you can read the
    orientation of".
    """
    import tempfile

    from isaacsimenvs.pose_reaching_6d.scene_utils.objects.generate_objects import (
        generate_handle_urdf,
    )

    path = Path(tempfile.mkdtemp(prefix="isaaclab_view_cube_")) / "cube.urdf"
    generate_handle_urdf(path, (edge_m, edge_m, edge_m), 400.0)
    return path.read_text(encoding="utf-8")


def build_html(frames: list[dict[str, Any]], *, edge_m: float = DEX_CUBE_EDGE_M) -> str:
    """The viewer page for a captured rollout of the reference env."""
    from coevolution.pose_viewer import build_pose_viewer_html

    return build_pose_viewer_html(
        frames=frames,
        object_urdf_text=object_urdf_text(edge_m),
        table_urdf_text="",            # the reference has no table
        # URL-backed, like every other robot in the viewer: the page fetches this from
        # master and resolves its meshes relative to it. Both are on master.
        robot_urdf_relpath=ROBOT_URDF_RELPATH,
        url_check="skip",
    )


__all__ = ["DEX_CUBE_EDGE_M", "PALM_BODY", "ROBOT_URDF_RELPATH", "build_html",
           "capture_frame", "object_urdf_text"]
