"""Allegro hand (16 DoF, 4 fingers) on a KUKA iiwa14.

The comparison hand. Its arm is imported from ``iiwa14_arm``, byte-identical to
SHARPA's, and its URDF is generated by ``genmech/tools/build_allegro_urdf.py``,
which grafts the Allegro hand onto the SHARPA robot's own iiwa14 chain — the
stock Allegro asset ships on an iiwa7, and using it would confound every result
with an arm change (docs/methodology.md §1).

Unlike SHARPA, this robot has **no pretrained checkpoint to validate against**.
Its correctness rests on ``tests/test_robot_spec_invariants.py``, on visual
inspection in ``genmech/tools/reachability_viewer.py``, and on the values below
being traceable. So each one says where it came from.

Provenance:

- **hand gains** (stiffness 3.0, damping 0.1, all 16 joints): Isaac Lab's
  ``KUKA_ALLEGRO_CFG``. Flagged risk: Isaac Lab pairs these with
  ``solver_position_iteration_count=32`` while this task runs 8, so they may
  prove too soft to hold a heavy tool. Verify with a grasp-hold check before
  trusting a training result.
- **hand armature** (0.001): not specified by Isaac Lab. Chosen to sit inside
  SHARPA's measured range (0.00042 - 0.0032). Authored, not derived.
- **home pose**: fingers fully extended to match SHARPA's convention, thumb
  opposed using Isaac Lab's ``KUKA_ALLEGRO_CFG`` values. See
  ``HAND_DEFAULT_JOINT_POS`` for why the thumb cannot simply be zeroed.
- **arm gains, home pose, base placement, arm adjacency**: shared with SHARPA.

Geometry offsets, measured with yourdfpy FK against the generated URDF:

- ``palm_center_offset`` is **identical to SHARPA's**, and deliberately so. Both
  hands mount on the same arm and both merge their palm into ``iiwa14_link_7``,
  so the same offset denotes literally the same physical point for a given arm
  pose. That holds the observation frame — the frame ``palm_pos``,
  ``keypoints_rel_palm``, and ``fingertip_pos_rel_palm`` are all expressed in —
  constant across hands, which is the requirement; a per-hand value would mean
  the two policies see different observations of the same world.

  It is also geometrically appropriate rather than merely convenient. Measured
  in the ``iiwa14_link_7`` frame at each hand's home pose, the two hands land on
  top of each other: knuckle centroid z = 0.182 for **both**, fingertip centroid
  z = 0.251 (SHARPA) vs 0.248 (Allegro). SHARPA's authored (0, -0.02, 0.16) sits
  2.9 cm proximal of its own knuckle centroid and 3.1 cm proximal of Allegro's —
  the same relationship to both hands.

  Worth recording: SHARPA's value matches no geometric landmark (nearest is its
  knuckle centroid, 2.9 cm away), so it is hand-authored and cannot be
  reproduced by a rule. That is precisely why re-deriving a separate value for
  Allegro would have been arbitrary.

- ``fingertip_offsets`` are the centroids of each distal link's collision mesh.
  That rule reproduces SHARPA's authored (0.02, 0.002, 0.0) to within 8.5 mm,
  the closest simple rule found, so it is applied here rather than invented.
  Per-fingertip because the thumb carries a different sensor mesh
  (``biotac_sensor_thumb.obj``) than the fingers (``biotac_sensor.obj``).
"""

from __future__ import annotations

from genmech.robots.adjacency.allegro_iiwa14 import ALLEGRO_IIWA14_ADJACENT_LINKS
from genmech.robots.iiwa14_arm import (
    ARM_DAMPING,
    ARM_DEFAULT_JOINT_POS,
    ARM_JOINT_NAMES,
    ARM_LINK_PRIM_REGEX,
    ARM_NAME,
    ARM_STIFFNESS,
    ARM_TIP_LINK,
    BASE_POS,
    BASE_ROT,
    START_ARM_HIGHER_DELTAS,
)
from genmech.robots.spec import RobotSpec, Vec3


FINGERS: tuple[str, ...] = ("index", "middle", "ring", "thumb")

# 4 fingers x 4 joints. Ordered finger-major to mirror SHARPA's canonical
# layout (all of one digit's joints together, thumb last among the fingers it
# groups with).
HAND_JOINT_NAMES: tuple[str, ...] = tuple(
    f"{finger}_joint_{i}" for finger in FINGERS for i in range(4)
)

# Isaac Lab KUKA_ALLEGRO_CFG: uniform across all 16 joints.
HAND_STIFFNESS: dict[str, float] = {name: 3.0 for name in HAND_JOINT_NAMES}
HAND_DAMPING: dict[str, float] = {name: 0.1 for name in HAND_JOINT_NAMES}
# Not given by Isaac Lab; sits inside SHARPA's measured 0.00042-0.0032 range.
HAND_ARMATURE: dict[str, float] = {name: 0.001 for name in HAND_JOINT_NAMES}

# Fingers fully extended, thumb opposed.
#
# SHARPA's home pose is all-zeros, which for its flexion joints (lower limit
# 0.0) is the hard extension stop -- the hand starts fully open. Allegro must
# start the same way or the two hands begin episodes at different points in
# their own ranges, which changes how fast each can enclose an object. That is a
# config choice, not a hardware property, and it would leak straight into the
# comparison.
#
# So the four flexion joints per finger are 0.0 (straight; -0.279 is
# hyperextension, not a pose to start from) and abduction is centred.
#
# The thumb's three flexion joints extend the same way: joints 2 and 3 share the
# fingers' exact limits ([-0.279, 1.728] / [-0.279, 1.763]) and joint 1 reaches
# 0.0 too, so all three go straight.
#
# `thumb_joint_0` is the one genuine exception. Its limits are [0.279, 1.571],
# so 0.0 is outside its range and would be clamped -- Allegro's zero is not
# SHARPA's zero. This joint swings the thumb across the palm rather than
# extending it, and its neutral is defined by its own range, so it keeps Isaac
# Lab's 1.5 (95% of range), opposing the thumb across the fingers. That is the
# analogue of where SHARPA's thumb already sits at zero.
HAND_DEFAULT_JOINT_POS: dict[str, float] = {
    **{f"{f}_joint_{i}": 0.0 for f in ("index", "middle", "ring") for i in range(4)},
    "thumb_joint_0": 1.5,
    "thumb_joint_1": 0.0,
    "thumb_joint_2": 0.0,
    "thumb_joint_3": 0.0,
}

# Distal links. These carry the biotac sensor geometry and are what the
# fingertip observations and the fingertip-approach reward key off.
FINGERTIP_BODY_NAMES: tuple[str, ...] = tuple(f"{f}_link_3" for f in FINGERS)

# Collision-mesh centroids, in each distal link's own frame.
_PAD_FINGER: Vec3 = (0.0357, 0.0015, -0.0001)   # biotac_sensor.obj
_PAD_THUMB: Vec3 = (0.0470, 0.0010, -0.0002)    # biotac_sensor_thumb.obj


ALLEGRO_IIWA14 = RobotSpec(
    name="allegro_iiwa14",
    arm_name=ARM_NAME,
    hand_name="allegro",
    urdf_path="assets/urdf/kuka_allegro_iiwa14_description/iiwa14_allegro.urdf",

    arm_joint_names=ARM_JOINT_NAMES,
    hand_joint_names=HAND_JOINT_NAMES,

    # allegro_mount and palm_link merge into the arm's last link, same as
    # SHARPA's mount chain does.
    palm_body_name=ARM_TIP_LINK,
    fingertip_body_names=FINGERTIP_BODY_NAMES,

    arm_stiffness=ARM_STIFFNESS,
    arm_damping=ARM_DAMPING,
    hand_stiffness=HAND_STIFFNESS,
    hand_damping=HAND_DAMPING,
    hand_armature=HAND_ARMATURE,

    arm_default_joint_pos=ARM_DEFAULT_JOINT_POS,
    hand_default_joint_pos=HAND_DEFAULT_JOINT_POS,
    start_arm_higher_deltas=START_ARM_HIGHER_DELTAS,

    # Identical to SHARPA's: same arm, same palm body, so the same offset is the
    # same physical point. See the module docstring.
    palm_center_offset=(-0.0, -0.02, 0.16),
    fingertip_offsets=(_PAD_FINGER, _PAD_FINGER, _PAD_FINGER, _PAD_THUMB),

    adjacent_links=ALLEGRO_IIWA14_ADJACENT_LINKS,
    link_prim_regexes=(
        ARM_LINK_PRIM_REGEX,
        "/World/envs/env_.*/Robot/palm_link/visuals",
        "/World/envs/env_.*/Robot/index_link_.*/visuals",
        "/World/envs/env_.*/Robot/middle_link_.*/visuals",
        "/World/envs/env_.*/Robot/ring_link_.*/visuals",
        "/World/envs/env_.*/Robot/thumb_link_.*/visuals",
    ),

    base_pos=BASE_POS,
    base_rot=BASE_ROT,

    notes=(
        "Comparison hand. URDF generated by genmech/tools/build_allegro_urdf.py. "
        "Hand gains from Isaac Lab KUKA_ALLEGRO_CFG; armature authored. No "
        "pretrained checkpoint exists for this robot, so its correctness rests "
        "on the spec invariants and visual inspection."
    ),
)


__all__ = ["ALLEGRO_IIWA14"]
