"""Author one generated design's robot, with the arm brought in by reference.

The arm is converted once from an arm-only URDF and referenced by every
design; the palm is merged into ``iiwa14_link_7`` as an OVER on the referenced
link (mass, inertia and collision box), as ``merge_fixed_joints`` does; the
hand is authored per design by ``author_usd.author_hand``.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

from hand_sampler import params as P
from hand_sampler.allegro_urdf import ARM_JOINTS, ARM_LINKS, SHARPA_URDF, _rewrite_meshes
from hand_sampler.paths import resolve as resolve_repo_path
from hand_sampler.rotations import mat_to_pos_quat

from .author_usd import (
    LINK_PARTS, PALM_BODY, _mat_from_seg, _set_xform, attr, author_hand, define,
    flange_to_palm, merged_palm_body_props,
)

ARM_PRIM = "/arm"
# The PhysX props a converted robot gets at spawn, authored inline.
_MAX_DEPEN_VELOCITY = 1000.0


def _add_api(spec, name: str) -> None:
    """Append an API schema without clobbering what the spec or its reference has."""
    from pxr import Sdf

    op = spec.GetInfo("apiSchemas") if spec.HasInfo("apiSchemas") else None
    if op is not None and op.isExplicit:
        items = list(op.explicitItems)
        if name not in items:
            spec.SetInfo("apiSchemas", Sdf.TokenListOp.CreateExplicit(items + [name]))
        return
    existing = list(op.appendedItems) if op is not None else []
    if name in existing:
        return
    new_op = Sdf.TokenListOp()
    new_op.appendedItems = existing + [name]
    spec.SetInfo("apiSchemas", new_op)


def arm_only_urdf(out_path: Path) -> Path:
    """The iiwa14 arm with no hand, copied verbatim from the SHARPA URDF."""
    sharpa = ET.parse(resolve_repo_path(SHARPA_URDF)).getroot()
    root = ET.Element("robot", {"name": "iiwa14_arm_only"})
    root.append(ET.Comment(" GENERATED by scene_utils/author_robot.py: the iiwa14 arm "
                           "alone, converted once and referenced by every authored design. "))
    # Absolute mesh paths: from a temp dir the URDF's relative prefix resolves to
    # nothing, and the importer only warns, leaving the arm with no colliders.
    mesh_root = str(resolve_repo_path(SHARPA_URDF).parent) + "/"
    for mat in sharpa.findall("material"):
        root.append(mat)
    for link in sharpa.findall("link"):
        if link.get("name") in ARM_LINKS:
            _rewrite_meshes(link, "", mesh_root)
            root.append(link)
    for joint in sharpa.findall("joint"):
        if joint.get("name") in ARM_JOINTS:
            root.append(joint)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(root).write(out_path, encoding="utf-8", xml_declaration=True)
    return out_path


def author_robot_prims(layer, root: str, hand: P.HandParams, spec, *,
                       arm_usd: str, arm_root_prim: str, link7_world,
                       contact_offset: float, rest_offset: float,
                       adjacency: dict | None = None,
                       in_change_block: bool = False) -> tuple[str, dict]:
    """Author one design under ``root``. Returns ``(root, {link: n_colliders})``.

    ``in_change_block`` says the caller already holds a ChangeBlock (they do not nest).
    """
    import contextlib

    from pxr import Gf, Sdf

    collider_links: dict[str, int] = {}
    with (contextlib.nullcontext() if in_change_block else Sdf.ChangeBlock()):
        # No ArticulationRootAPI here: the referenced arm brings its own root_joint
        # and PhysX allows one per tree. The hand joints attach to iiwa14_link_7.
        define(layer, root, "Xform")
        arm = define(layer, f"{root}{ARM_PRIM}", "Xform")
        arm.referenceList.explicitItems.append(Sdf.Reference(str(arm_usd), Sdf.Path(arm_root_prim)))

        palm_path = f"{root}{ARM_PRIM}/{PALM_BODY}"
        summary = author_hand(layer, root, hand, spec, palm_body_path=palm_path,
                              link7_world=link7_world)
        collider_links.update(summary["collider_links"])

        # The merged palm, as an OVER on the referenced link.
        mass, inertia, com, axes = merged_palm_body_props(hand)
        palm = Sdf.CreatePrimInLayer(layer, Sdf.Path(palm_path))
        attr(palm, "physics:mass", Sdf.ValueTypeNames.Float, float(mass))
        attr(palm, "physics:diagonalInertia", Sdf.ValueTypeNames.Float3,
             Gf.Vec3f(*[float(v) for v in inertia]))
        attr(palm, "physics:centerOfMass", Sdf.ValueTypeNames.Float3,
             Gf.Vec3f(*[float(v) for v in com]))
        attr(palm, "physics:principalAxes", Sdf.ValueTypeNames.Quatf,
             Gf.Quatf(float(axes[0]), Gf.Vec3f(*[float(v) for v in axes[1:]])))

        # The palm's collision box, placed by the transform merge_fixed_joints folds away.
        t = _mat_from_seg(flange_to_palm())
        centre = np.asarray([float(v) for v in P.palm_center(hand.palm_extents)])
        _, quat = mat_to_pos_quat(t)
        offset = (t @ np.append(centre, 1.0))[:3]
        collider_links[PALM_BODY] = collider_links.get(PALM_BODY, 0) + 1
        box = define(layer, f"{palm_path}/palm_collision", "Cube",
                     ["PhysicsCollisionAPI", "PhysxCollisionAPI"])
        attr(box, "size", Sdf.ValueTypeNames.Double, 1.0)
        _set_xform(box, offset, quat, scale=tuple(float(v) for v in hand.palm_extents))
        attr(box, "physxCollision:contactOffset", Sdf.ValueTypeNames.Float, contact_offset)
        attr(box, "physxCollision:restOffset", Sdf.ValueTypeNames.Float, rest_offset)

        # PhysX props on the hand's bodies and capsules.
        for i in range(P.N_FINGER_SLOTS):
            for part, _tier in LINK_PARTS:
                body = Sdf.CreatePrimInLayer(layer, Sdf.Path(f"{root}/gen_f{i}_{part}"))
                _add_api(body, "PhysxRigidBodyAPI")
                attr(body, "physxRigidBody:disableGravity", Sdf.ValueTypeNames.Bool, True)
                attr(body, "physxRigidBody:maxDepenetrationVelocity",
                     Sdf.ValueTypeNames.Float, _MAX_DEPEN_VELOCITY)
                cap = Sdf.CreatePrimInLayer(
                    layer, Sdf.Path(f"{root}/gen_f{i}_{part}/collisions/mesh_0/capsule"))
                if cap.specifier == Sdf.SpecifierDef:
                    _add_api(cap, "PhysxCollisionAPI")
                    attr(cap, "physxCollision:contactOffset", Sdf.ValueTypeNames.Float,
                         contact_offset)
                    attr(cap, "physxCollision:restOffset", Sdf.ValueTypeNames.Float,
                         rest_offset)

        # Self-collision filters for the spec's adjacency, in this same pass.
        if adjacency:
            body_path = {f"gen_f{i}_{part}": f"{root}/gen_f{i}_{part}"
                         for i in range(P.N_FINGER_SLOTS) for part, _t in LINK_PARTS}
            body_path[PALM_BODY] = palm_path
            for n in range(8):
                body_path[f"iiwa14_link_{n}"] = f"{root}{ARM_PRIM}/iiwa14_link_{n}"
            for link, neighbours in adjacency.items():
                a = body_path.get(link)
                targets = [body_path[b] for b in neighbours if b in body_path]
                if a is None or not targets:
                    continue
                spec_a = Sdf.CreatePrimInLayer(layer, Sdf.Path(a))
                _add_api(spec_a, "PhysicsFilteredPairsAPI")
                r = Sdf.RelationshipSpec(spec_a, "physics:filteredPairs", False)
                for tgt in targets:
                    r.targetPathList.explicitItems.append(Sdf.Path(tgt))
    return root, collider_links


def flatten_robot_usd(usd_path: str, out_path: Path, *,
                      contact_offset: float, rest_offset: float) -> tuple[str, str]:
    """Inline the converter's sub-layers into one file with the robot PhysX
    props set once; returns ``(path, root_prim_path)``. Nested references do
    not resolve a second level down, so an unflattened file composes with no
    colliders when an env prim references it."""
    from pxr import PhysxSchema, Sdf, Usd, UsdPhysics

    stage = Usd.Stage.Open(usd_path, Usd.Stage.LoadAll)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    stage.Flatten().Export(str(out_path))

    flat = Usd.Stage.Open(str(out_path))
    root = flat.GetDefaultPrim() or next(
        p for p in flat.GetPseudoRoot().GetChildren() if p.IsValid())
    for prim in Usd.PrimRange(root):
        if prim.HasAPI(UsdPhysics.RigidBodyAPI):
            PhysxSchema.PhysxRigidBodyAPI.Apply(prim)
            prim.CreateAttribute("physxRigidBody:disableGravity",
                                 Sdf.ValueTypeNames.Bool).Set(True)
            prim.CreateAttribute("physxRigidBody:maxDepenetrationVelocity",
                                 Sdf.ValueTypeNames.Float).Set(_MAX_DEPEN_VELOCITY)
        if prim.HasAPI(UsdPhysics.ArticulationRootAPI):
            PhysxSchema.PhysxArticulationAPI.Apply(prim)
            prim.CreateAttribute("physxArticulation:enabledSelfCollisions",
                                 Sdf.ValueTypeNames.Bool).Set(True)
            prim.CreateAttribute("physxArticulation:solverPositionIterationCount",
                                 Sdf.ValueTypeNames.Int).Set(8)
            prim.CreateAttribute("physxArticulation:solverVelocityIterationCount",
                                 Sdf.ValueTypeNames.Int).Set(0)
        if prim.HasAPI(UsdPhysics.CollisionAPI):
            PhysxSchema.PhysxCollisionAPI.Apply(prim)
            prim.CreateAttribute("physxCollision:contactOffset",
                                 Sdf.ValueTypeNames.Float).Set(contact_offset)
            prim.CreateAttribute("physxCollision:restOffset",
                                 Sdf.ValueTypeNames.Float).Set(rest_offset)
    flat.GetRootLayer().Save()
    return str(out_path), str(root.GetPath())


__all__ = ["ARM_PRIM", "arm_only_urdf", "author_robot_prims", "flatten_robot_usd"]
