"""Author a generated design's robot directly, instead of converting a URDF.

Kit's UrdfConverter costs ~0.9 s per hand, ~90% of it re-importing the arm's
16 STL meshes. So the arm is converted once from an arm-only URDF and brought
in by reference; the hand (capsules and a box) is authored with Sdf specs
(~8 ms); the palm is merged into ``iiwa14_link_7`` as an OVER on the referenced
link (mass, inertia and collision box), as ``merge_fixed_joints`` does.

The target is the converter's POST-MERGE robot: ``merge_fixed_joints`` folds
``gen_palm`` into ``iiwa14_link_7`` and each fingertip into its distal
phalanx, so the authored asset is

    /<root>                                 Xform
      /arm                                  reference: iiwa14_link_0..7 + joints
      /gen_f{i}_{CMC_VL,MC,MCP_VL,PP,MP,DP}  30 Xform bodies
        /collisions/mesh_0/capsule          Capsule, axis Z
      /joints/gen_f{i}_{slot}               30 PhysicsRevoluteJoint
      /root_joint                           PhysicsFixedJoint + ArticulationRootAPI

Conventions, read off a converted asset: a capsule is ``radius=r,
height=length-2r, axis=Z`` under an Xform at ``(length/2, 0, 0)`` rotated 90
deg about Y; joint limits and velocities are in DEGREES; ``localPos0/Rot0``
is the joint origin in the parent frame, ``localPos1/Rot1`` identity; inertia
is ``diagonalInertia`` plus a ``principalAxes`` quaternion; a virtual link has
mass and inertia 1e-6.
"""

from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

from hand_sampler import resolve as resolve_repo_path
from hand_sampler.robot_param_constants import ARM_JOINTS, ARM_LINKS, SHARPA_URDF
from hand_sampler.design_space import mat_to_pos_quat, rpy_to_mat, rpy_to_quat_wxyz

from .sdf import MAX_DEPEN_VELOCITY, attr, define, rel, set_xform

ARM_PRIM = "/arm"
PALM_BODY = "iiwa14_link_7"  # post-merge palm body
# Chain order and the tier that gives each link its geometry
# (build_hand_urdf.LINK_PARTS minus `tip`, which merges into DP).
LINK_PARTS: tuple[tuple[str, str | None], ...] = (
    ("CMC_VL", None), ("MC", "mc"), ("MCP_VL", None),
    ("PP", "pp"), ("MP", "mp"), ("DP", "dp"),
)
# link_7 -> link_ee (iiwa14_joint_ee); merge_fixed_joints folds it into the palm mount.
LINK7_TO_FLANGE_Z_M: float = 0.045
# What the converter writes for drives whatever gains are asked for. Isaac Lab
# overwrites them at runtime; matching keeps authored and converted assets comparable.
CONVERTER_DRIVE_STIFFNESS: float = 625.0
CONVERTER_DRIVE_DAMPING: float = 0.0


# --- geometry and mass, shared with the URDF builder ---------------------------













# --- the merged palm body ---------------------------------------------------------

_LINK7_INERTIAL: tuple | None = None






# --- the hand ---------------------------------------------------------------------



# --- the robot --------------------------------------------------------------------

def _rewrite_meshes(elem: ET.Element, frm: str, to: str) -> int:
    """Repoint every <mesh filename> under ``elem`` from one prefix to another."""
    n = 0
    for mesh in elem.iter("mesh"):
        fn = mesh.get("filename", "")
        if fn.startswith(frm):
            mesh.set("filename", to + fn[len(frm):])
            n += 1
        elif frm == "" and not fn.startswith(to) and not fn.startswith("/"):
            mesh.set("filename", to + fn)
            n += 1
    return n


def arm_only_urdf(out_path: Path) -> Path:
    """The iiwa14 arm with no hand, copied verbatim from the SHARPA URDF.

    A generated design authors its own bodies but attaches them to a real arm,
    which still comes from an asset. Converted once and referenced by every env.
    """
    sharpa = ET.parse(resolve_repo_path(SHARPA_URDF)).getroot()
    root = ET.Element("robot", {"name": "iiwa14_arm_only"})
    root.append(ET.Comment(" GENERATED by scene_utils/author_robot.py: the iiwa14 arm "
                           "alone, converted once and referenced by every authored design. "))
    # Absolute mesh paths: from a temp dir the URDF's relative prefix resolves to
    # nothing, and the importer only warns, leaving the arm with no colliders.
    mesh_root = str(resolve_repo_path(SHARPA_URDF).parent) + "/"
    for mat in sharpa.findall("material"):
        root.append(mat)
    for link in sharpa.findall("link"):
        if link.get("name") in ARM_LINKS:
            _rewrite_meshes(link, "", mesh_root)
            root.append(link)
    for joint in sharpa.findall("joint"):
        if joint.get("name") in ARM_JOINTS:
            root.append(joint)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(root).write(out_path, encoding="utf-8", xml_declaration=True)
    return out_path


def _add_api(spec, name: str) -> None:
    """Append an API schema without clobbering what the spec or its reference has."""
    from pxr import Sdf

    op = spec.GetInfo("apiSchemas") if spec.HasInfo("apiSchemas") else None
    if op is not None and op.isExplicit:
        items = list(op.explicitItems)
        if name not in items:
            spec.SetInfo("apiSchemas", Sdf.TokenListOp.CreateExplicit(items + [name]))
        return
    existing = list(op.appendedItems) if op is not None else []
    if name in existing:
        return
    new_op = Sdf.TokenListOp()
    new_op.appendedItems = existing + [name]
    spec.SetInfo("apiSchemas", new_op)






def _strip_render_only(stage, root) -> tuple[int, int]:
    """Drop the render-only subtrees (per-link ``visuals``, the ``Looks`` scope).

    Every env references this file, and composition costs ~1.5 us per prim per
    env, so the visual meshes and their shaders cost minutes at 24k envs and
    PhysX never reads them. A subtree goes only if nothing under it carries
    physics, which keeps collision geometry and physics materials. The robot
    is invisible to a camera or the GUI afterwards.
    """
    from pxr import Usd, UsdPhysics

    def walk(prim):
        # The converter puts geometry behind instance proxies; a plain PrimRange
        # stops at the instance root and reports a subtree as empty.
        return Usd.PrimRange(prim, Usd.TraverseInstanceProxies(Usd.PrimDefaultPredicate))

    def physical(prim) -> bool:
        return any(p.HasAPI(UsdPhysics.CollisionAPI) or p.HasAPI(UsdPhysics.RigidBodyAPI)
                   or p.HasAPI(UsdPhysics.ArticulationRootAPI)
                   or p.HasAPI(UsdPhysics.MaterialAPI) or p.IsA(UsdPhysics.Joint)
                   for p in walk(prim))

    def colliders() -> int:
        return sum(1 for p in walk(root) if p.HasAPI(UsdPhysics.CollisionAPI))

    before, colliders_before = sum(1 for _ in walk(root)), colliders()
    doomed, it = [], iter(walk(root))
    for prim in it:
        if prim.GetName() in ("visuals", "Looks") and not physical(prim):
            doomed.append(prim.GetPath())
            it.PruneChildren()
    for path in doomed:
        stage.RemovePrim(path)
    # The whole point is that only rendering is lost. A collider going with it
    # would be silent: the robot still loads, it just stops touching anything.
    if colliders() != colliders_before:
        raise RuntimeError(
            f"stripping render-only prims changed the collider count "
            f"({colliders_before} -> {colliders()}); refusing to build the scene")
    return before - sum(1 for _ in walk(root)), before


def keep_visuals_requested() -> bool:
    """``GENMECH_KEEP_VISUALS=1`` keeps the robot renderable.

    Stripping the render-only prims is a 24k-env throughput measure and it
    makes the robot invisible to any camera. A handful of envs being recorded
    to video wants the opposite trade, and at that scale the composition cost
    it buys back is irrelevant.
    """
    import os
    return os.environ.get("GENMECH_KEEP_VISUALS", "0") not in ("0", "", "false")


def flatten_robot_usd(usd_path: str, out_path: Path, *,
                      contact_offset: float, rest_offset: float,
                      strip_render_only: bool | None = None) -> tuple[str, str]:
    """Inline the converter's sub-layers into one file with the robot PhysX
    props set once and the render-only prims dropped; returns
    ``(path, root_prim_path)``. Nested references do not resolve a second level
    down, so an unflattened file composes with no colliders when an env prim
    references it.

    ``strip_render_only=False`` (or ``GENMECH_KEEP_VISUALS=1``) keeps the
    visual meshes so the robot can be rendered. The output then goes to a
    DIFFERENT filename, because a stripped and an unstripped flatten are not
    interchangeable and silently reusing one for the other would either cost
    throughput or produce an empty video.
    """
    from pxr import PhysxSchema, Sdf, Usd, UsdPhysics

    if strip_render_only is None:
        strip_render_only = not keep_visuals_requested()
    if not strip_render_only:
        out_path = out_path.with_name(
            out_path.stem + "_vis" + out_path.suffix)

    stage = Usd.Stage.Open(usd_path, Usd.Stage.LoadAll)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    stage.Flatten().Export(str(out_path))

    flat = Usd.Stage.Open(str(out_path))
    root = flat.GetDefaultPrim() or next(
        p for p in flat.GetPseudoRoot().GetChildren() if p.IsValid())
    removed = _strip_render_only(flat, root)[0] if strip_render_only else 0
    # Every remaining prim is composed once per env, so the breakdown says
    # where the next cut is: wrapper Xforms, colliders, joints.
    # Only prims outside a prototype are composed per env; instanced geometry
    # is shared, so it is free however many envs reference it.
    kinds: dict[str, int] = {}
    shared = 0
    for prim in Usd.PrimRange(root, Usd.TraverseInstanceProxies(Usd.PrimDefaultPredicate)):
        if prim.IsInstanceProxy():
            shared += 1
            continue
        kinds[prim.GetTypeName() or "(none)"] = kinds.get(prim.GetTypeName() or "(none)", 0) + 1
    breakdown = ", ".join(f"{k} x{v}" for k, v in sorted(kinds.items(), key=lambda kv: -kv[1]))
    print(f"[scene_utils] {out_path.name}: "
          f"{'dropped %d render-only prims' % removed if strip_render_only else 'KEPT render-only prims (renderable)'}; "
          f"{sum(kinds.values())} composed per env ({breakdown}), "
          f"{shared} more shared in prototypes", flush=True)
    for prim in Usd.PrimRange(root):
        if prim.HasAPI(UsdPhysics.RigidBodyAPI):
            PhysxSchema.PhysxRigidBodyAPI.Apply(prim)
            prim.CreateAttribute("physxRigidBody:disableGravity",
                                 Sdf.ValueTypeNames.Bool).Set(True)
            prim.CreateAttribute("physxRigidBody:maxDepenetrationVelocity",
                                 Sdf.ValueTypeNames.Float).Set(MAX_DEPEN_VELOCITY)
        if prim.HasAPI(UsdPhysics.ArticulationRootAPI):
            PhysxSchema.PhysxArticulationAPI.Apply(prim)
            prim.CreateAttribute("physxArticulation:enabledSelfCollisions",
                                 Sdf.ValueTypeNames.Bool).Set(True)
            prim.CreateAttribute("physxArticulation:solverPositionIterationCount",
                                 Sdf.ValueTypeNames.Int).Set(8)
            prim.CreateAttribute("physxArticulation:solverVelocityIterationCount",
                                 Sdf.ValueTypeNames.Int).Set(0)
        if prim.HasAPI(UsdPhysics.CollisionAPI):
            PhysxSchema.PhysxCollisionAPI.Apply(prim)
            prim.CreateAttribute("physxCollision:contactOffset",
                                 Sdf.ValueTypeNames.Float).Set(contact_offset)
            prim.CreateAttribute("physxCollision:restOffset",
                                 Sdf.ValueTypeNames.Float).Set(rest_offset)
    flat.GetRootLayer().Save()
    return str(out_path), str(root.GetPath())


__all__ = ["ARM_PRIM", "arm_only_urdf", "flatten_robot_usd",
           "keep_visuals_requested"]
